// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrzuifckyctcncvpokcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyenVpZmNreWN0Y25jdnBva2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MzA0MTksImV4cCI6MjA1OTQwNjQxOX0.MFrDXaq6wv_rGbK7Ntdbt7_BYHgxc3ZH40xNpol6X-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey: 'agritrade-auth-token',
    persistSession: true,
    detectSessionInUrl: false
  }
});